// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfsMK_1ntqVLk6K_KAB6uVNMZitOJb1Y',
    appId: '1:118957221303:web:6658cac99fc1d439e2b432',
    messagingSenderId: '118957221303',
    projectId: 'eldercare-sg',
    authDomain: 'eldercare-sg.firebaseapp.com',
    storageBucket: 'eldercare-sg.firebasestorage.app',
    measurementId: 'G-NDPZ428EL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5qpif4TPGkN6ztZOZZQZInJF2eGZOCU',
    appId: '1:118957221303:android:c67f49ce02986b1ce2b432',
    messagingSenderId: '118957221303',
    projectId: 'eldercare-sg',
    storageBucket: 'eldercare-sg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_pQBThPkAyRM4htX64ryyF5DBJCkClQ',
    appId: '1:118957221303:ios:ad18fd804ec8d08de2b432',
    messagingSenderId: '118957221303',
    projectId: 'eldercare-sg',
    storageBucket: 'eldercare-sg.firebasestorage.app',
    iosBundleId: 'com.example.checkinV3Db',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7_pQBThPkAyRM4htX64ryyF5DBJCkClQ',
    appId: '1:118957221303:ios:ad18fd804ec8d08de2b432',
    messagingSenderId: '118957221303',
    projectId: 'eldercare-sg',
    storageBucket: 'eldercare-sg.firebasestorage.app',
    iosBundleId: 'com.example.checkinV3Db',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKfsMK_1ntqVLk6K_KAB6uVNMZitOJb1Y',
    appId: '1:118957221303:web:7180a06e4db56d1de2b432',
    messagingSenderId: '118957221303',
    projectId: 'eldercare-sg',
    authDomain: 'eldercare-sg.firebaseapp.com',
    storageBucket: 'eldercare-sg.firebasestorage.app',
    measurementId: 'G-WWC118SMLS',
  );
}
